services:
  uai_food_postgres:
    container_name: uai-food-db
    image: bitnami/postgresql
    ports:
      - "5324:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=uai-food-db
    networks:
      - network_uai_food
    volumes:
      - postgres_data:/bitnami/postgresql

  uai_food_chat_postgres:
    container_name: uai-food-db-chat
    image: bitnami/postgresql
    ports:
      - "5325:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=uai-food-db-chat
    networks:
      - network_uai_food
    volumes:
      - postgres_data:/bitnami/postgresql

  uai_food_redis:
    container_name: uai-food-redis
    image: redis:7
    ports:
      - "6973:6379"
    networks:
      - network_uai_food
    volumes:
      - redis_data:/data

  uai_food_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5276:5672"
      - "15276:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  network_uai_food:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
    driver: local
